// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace _2FA_Service.Models;

public partial class _2FA_ServiceContext : DbContext
{
    public _2FA_ServiceContext(DbContextOptions<_2FA_ServiceContext> options)
        : base(options)
    {
    }

    public virtual DbSet<PhoneNumberCode> PhoneNumberCodes { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<PhoneNumberCode>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__PhoneNum__3214EC07B2A80139");

            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.PhoneNumber)
                .IsRequired()
                .HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}