// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace _2FA_Service.Models;

public partial class PhoneNumberCode
{
    public int Id { get; set; }

    public string PhoneNumber { get; set; }

    public string Code { get; set; }

    public DateTime CreatedDate { get; set; }
}